// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'eventchart.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$_Eventchart _$$_EventchartFromJson(Map<String, dynamic> json) =>
    _$_Eventchart(
      rangeaxisminvalue: (json['rangeaxisminvalue'] as num?)?.toDouble(),
      rangeaxisdecimals: json['rangeaxisdecimals'] as int?,
      attributevaluedimensionid: json['attributevaluedimensionid'] as int?,
      domainaxislabel: json['domainaxislabel'] as String?,
      hideemptyrowitems: json['hideemptyrowitems'] as String,
      lastupdated: json['lastupdated'] == null
          ? null
          : DateTime.parse(json['lastupdated'] as String),
      type: json['type'] as String,
      orgunitfield: json['orgunitfield'] as String?,
      favorites: json['favorites'],
      enddate: json['enddate'] == null
          ? null
          : DateTime.parse(json['enddate'] as String),
      uid: json['uid'] as String?,
      programstageid: json['programstageid'] as int?,
      targetlinelabel: json['targetlinelabel'] as String?,
      userorgunittype: json['userorgunittype'] as String?,
      hidenadata: json['hidenadata'] as bool?,
      created: json['created'] == null
          ? null
          : DateTime.parse(json['created'] as String),
      subscribers: json['subscribers'],
      sortorder: json['sortorder'] as int?,
      dataelementvaluedimensionid: json['dataelementvaluedimensionid'] as int?,
      eventchartid: json['eventchartid'] as int,
      collapsedatadimensions: json['collapsedatadimensions'] as bool?,
      completedonly: json['completedonly'] as bool?,
      name: json['name'] as String,
      relativeperiodsid: json['relativeperiodsid'] as int?,
      regressiontype: json['regressiontype'] as String,
      userorganisationunitchildren:
          json['userorganisationunitchildren'] as bool?,
      cumulativevalues: json['cumulativevalues'] as bool?,
      lastupdatedby: json['lastupdatedby'] as int?,
      sharing: json['sharing'],
      aggregationtype: json['aggregationtype'] as String?,
      hidelegend: json['hidelegend'] as bool?,
      percentstackedvalues: json['percentstackedvalues'] as bool?,
      nospacebetweencolumns: json['nospacebetweencolumns'] as bool?,
      baselinevalue: (json['baselinevalue'] as num?)?.toDouble(),
      description: json['description'] as String?,
      baselinelabel: json['baselinelabel'] as String?,
      rangeaxismaxvalue: (json['rangeaxismaxvalue'] as num?)?.toDouble(),
      userorganisationunit: json['userorganisationunit'] as bool?,
      startdate: json['startdate'] == null
          ? null
          : DateTime.parse(json['startdate'] as String),
      code: json['code'] as String?,
      title: json['title'] as String?,
      rewindrelativeperiods: json['rewindrelativeperiods'] as bool?,
      rangeaxissteps: json['rangeaxissteps'] as int?,
      targetlinevalue: (json['targetlinevalue'] as num?)?.toDouble(),
      userorganisationunitgrandchildren:
          json['userorganisationunitgrandchildren'] as bool?,
      timefield: json['timefield'] as String?,
      hidetitle: json['hidetitle'] as bool?,
      toplimit: json['toplimit'] as int?,
      programid: json['programid'] as int,
      showdata: json['showdata'] as bool?,
      eventstatus: json['eventstatus'] as String?,
      translations: json['translations'],
      hidesubtitle: json['hidesubtitle'] as bool?,
      programstatus: json['programstatus'] as String?,
      attributevalues: json['attributevalues'],
      subtitle: json['subtitle'] as String?,
      outputtype: json['outputtype'] as String?,
      externalaccess: json['externalaccess'] as bool?,
      userid: json['userid'] as int?,
      rangeaxislabel: json['rangeaxislabel'] as String?,
      publicaccess: json['publicaccess'] as String?,
    );

Map<String, dynamic> _$$_EventchartToJson(_$_Eventchart instance) =>
    <String, dynamic>{
      'rangeaxisminvalue': instance.rangeaxisminvalue,
      'rangeaxisdecimals': instance.rangeaxisdecimals,
      'attributevaluedimensionid': instance.attributevaluedimensionid,
      'domainaxislabel': instance.domainaxislabel,
      'hideemptyrowitems': instance.hideemptyrowitems,
      'lastupdated': instance.lastupdated?.toIso8601String(),
      'type': instance.type,
      'orgunitfield': instance.orgunitfield,
      'favorites': instance.favorites,
      'enddate': instance.enddate?.toIso8601String(),
      'uid': instance.uid,
      'programstageid': instance.programstageid,
      'targetlinelabel': instance.targetlinelabel,
      'userorgunittype': instance.userorgunittype,
      'hidenadata': instance.hidenadata,
      'created': instance.created?.toIso8601String(),
      'subscribers': instance.subscribers,
      'sortorder': instance.sortorder,
      'dataelementvaluedimensionid': instance.dataelementvaluedimensionid,
      'eventchartid': instance.eventchartid,
      'collapsedatadimensions': instance.collapsedatadimensions,
      'completedonly': instance.completedonly,
      'name': instance.name,
      'relativeperiodsid': instance.relativeperiodsid,
      'regressiontype': instance.regressiontype,
      'userorganisationunitchildren': instance.userorganisationunitchildren,
      'cumulativevalues': instance.cumulativevalues,
      'lastupdatedby': instance.lastupdatedby,
      'sharing': instance.sharing,
      'aggregationtype': instance.aggregationtype,
      'hidelegend': instance.hidelegend,
      'percentstackedvalues': instance.percentstackedvalues,
      'nospacebetweencolumns': instance.nospacebetweencolumns,
      'baselinevalue': instance.baselinevalue,
      'description': instance.description,
      'baselinelabel': instance.baselinelabel,
      'rangeaxismaxvalue': instance.rangeaxismaxvalue,
      'userorganisationunit': instance.userorganisationunit,
      'startdate': instance.startdate?.toIso8601String(),
      'code': instance.code,
      'title': instance.title,
      'rewindrelativeperiods': instance.rewindrelativeperiods,
      'rangeaxissteps': instance.rangeaxissteps,
      'targetlinevalue': instance.targetlinevalue,
      'userorganisationunitgrandchildren':
          instance.userorganisationunitgrandchildren,
      'timefield': instance.timefield,
      'hidetitle': instance.hidetitle,
      'toplimit': instance.toplimit,
      'programid': instance.programid,
      'showdata': instance.showdata,
      'eventstatus': instance.eventstatus,
      'translations': instance.translations,
      'hidesubtitle': instance.hidesubtitle,
      'programstatus': instance.programstatus,
      'attributevalues': instance.attributevalues,
      'subtitle': instance.subtitle,
      'outputtype': instance.outputtype,
      'externalaccess': instance.externalaccess,
      'userid': instance.userid,
      'rangeaxislabel': instance.rangeaxislabel,
      'publicaccess': instance.publicaccess,
    };
