// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'relativeperiods.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$_Relativeperiods _$$_RelativeperiodsFromJson(Map<String, dynamic> json) =>
    _$_Relativeperiods(
      last3months: json['last3months'] as bool,
      thisfinancialyear: json['thisfinancialyear'] as bool,
      monthslastyear: json['monthslastyear'] as bool,
      thismonth: json['thismonth'] as bool,
      lastbiweek: json['lastbiweek'] as bool?,
      last4biweeks: json['last4biweeks'] as bool?,
      last4weeks: json['last4weeks'] as bool,
      last52weeks: json['last52weeks'] as bool,
      last60days: json['last60days'] as bool,
      thissixmonth: json['thissixmonth'] as bool,
      thisyear: json['thisyear'] as bool,
      monthsthisyear: json['monthsthisyear'] as bool,
      reportingmonth: json['reportingmonth'] as bool?,
      lastfinancialyear: json['lastfinancialyear'] as bool,
      last12months: json['last12months'] as bool,
      last10years: json['last10years'] as bool,
      last2sixmonths: json['last2sixmonths'] as bool,
      last7days: json['last7days'] as bool,
      weeksthisyear: json['weeksthisyear'] as bool?,
      lastquarter: json['lastquarter'] as bool,
      thisbimonth: json['thisbimonth'] as bool,
      last5financialyears: json['last5financialyears'] as bool,
      thisbiweek: json['thisbiweek'] as bool?,
      lastsixmonth: json['lastsixmonth'] as bool,
      lastbimonth: json['lastbimonth'] as bool,
      last12weeks: json['last12weeks'] as bool,
      last6months: json['last6months'] as bool,
      yesterday: json['yesterday'] as bool,
      relativeperiodsid: json['relativeperiodsid'] as int,
      last5years: json['last5years'] as bool,
      last3days: json['last3days'] as bool,
      last6bimonths: json['last6bimonths'] as bool,
      bimonthsthisyear: json['bimonthsthisyear'] as bool?,
      thisquarter: json['thisquarter'] as bool,
      thisday: json['thisday'] as bool,
      lastyear: json['lastyear'] as bool,
      quarterslastyear: json['quarterslastyear'] as bool,
      reportingbimonth: json['reportingbimonth'] as bool?,
      lastweek: json['lastweek'] as bool,
      last90days: json['last90days'] as bool,
      last10financialyears: json['last10financialyears'] as bool,
      last30days: json['last30days'] as bool,
      lastmonth: json['lastmonth'] as bool,
      last180days: json['last180days'] as bool,
      thisweek: json['thisweek'] as bool,
      last4quarters: json['last4quarters'] as bool,
      quartersthisyear: json['quartersthisyear'] as bool,
      reportingquarter: json['reportingquarter'] as bool?,
      last14days: json['last14days'] as bool,
    );

Map<String, dynamic> _$$_RelativeperiodsToJson(_$_Relativeperiods instance) =>
    <String, dynamic>{
      'last3months': instance.last3months,
      'thisfinancialyear': instance.thisfinancialyear,
      'monthslastyear': instance.monthslastyear,
      'thismonth': instance.thismonth,
      'lastbiweek': instance.lastbiweek,
      'last4biweeks': instance.last4biweeks,
      'last4weeks': instance.last4weeks,
      'last52weeks': instance.last52weeks,
      'last60days': instance.last60days,
      'thissixmonth': instance.thissixmonth,
      'thisyear': instance.thisyear,
      'monthsthisyear': instance.monthsthisyear,
      'reportingmonth': instance.reportingmonth,
      'lastfinancialyear': instance.lastfinancialyear,
      'last12months': instance.last12months,
      'last10years': instance.last10years,
      'last2sixmonths': instance.last2sixmonths,
      'last7days': instance.last7days,
      'weeksthisyear': instance.weeksthisyear,
      'lastquarter': instance.lastquarter,
      'thisbimonth': instance.thisbimonth,
      'last5financialyears': instance.last5financialyears,
      'thisbiweek': instance.thisbiweek,
      'lastsixmonth': instance.lastsixmonth,
      'lastbimonth': instance.lastbimonth,
      'last12weeks': instance.last12weeks,
      'last6months': instance.last6months,
      'yesterday': instance.yesterday,
      'relativeperiodsid': instance.relativeperiodsid,
      'last5years': instance.last5years,
      'last3days': instance.last3days,
      'last6bimonths': instance.last6bimonths,
      'bimonthsthisyear': instance.bimonthsthisyear,
      'thisquarter': instance.thisquarter,
      'thisday': instance.thisday,
      'lastyear': instance.lastyear,
      'quarterslastyear': instance.quarterslastyear,
      'reportingbimonth': instance.reportingbimonth,
      'lastweek': instance.lastweek,
      'last90days': instance.last90days,
      'last10financialyears': instance.last10financialyears,
      'last30days': instance.last30days,
      'lastmonth': instance.lastmonth,
      'last180days': instance.last180days,
      'thisweek': instance.thisweek,
      'last4quarters': instance.last4quarters,
      'quartersthisyear': instance.quartersthisyear,
      'reportingquarter': instance.reportingquarter,
      'last14days': instance.last14days,
    };
