// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'visualization.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$_Visualization _$$_VisualizationFromJson(Map<String, dynamic> json) =>
    _$_Visualization(
      completedonly: json['completedonly'] as bool?,
      hideemptycolumns: json['hideemptycolumns'] as bool?,
      hidetitle: json['hidetitle'] as bool?,
      hideemptyrows: json['hideemptyrows'] as bool?,
      hideemptyrowitems: json['hideemptyrowitems'] as String?,
      paramgrandparentorganisationunit:
          json['paramgrandparentorganisationunit'] as bool?,
      rangeaxismaxvalue: (json['rangeaxismaxvalue'] as num?)?.toDouble(),
      legenddisplaystyle: json['legenddisplaystyle'] as String?,
      measurecriteria: json['measurecriteria'] as String?,
      series: json['series'],
      userorganisationunitchildren:
          json['userorganisationunitchildren'] as bool?,
      hidelegend: json['hidelegend'] as bool?,
      displaydensity: json['displaydensity'] as String?,
      translations: json['translations'],
      regression: json['regression'] as bool?,
      domainaxislabel: json['domainaxislabel'] as String?,
      publicaccess: json['publicaccess'] as String?,
      legenddisplaystrategy: json['legenddisplaystrategy'] as String?,
      description: json['description'] as String?,
      aggregationtype: json['aggregationtype'] as String?,
      subtitle: json['subtitle'] as String?,
      userorganisationunitgrandchildren:
          json['userorganisationunitgrandchildren'] as bool?,
      fixrowheaders: json['fixrowheaders'] as bool,
      code: json['code'] as String?,
      userid: json['userid'] as int?,
      legendsetid: json['legendsetid'] as int?,
      hidesubtitle: json['hidesubtitle'] as bool?,
      axes: json['axes'],
      name: json['name'] as String,
      serieskey: json['serieskey'],
      showdimensionlabels: json['showdimensionlabels'] as bool?,
      baselinevalue: (json['baselinevalue'] as num?)?.toDouble(),
      toplimit: json['toplimit'] as int?,
      paramorganisationunit: json['paramorganisationunit'] as bool?,
      startdate: json['startdate'] == null
          ? null
          : DateTime.parse(json['startdate'] as String),
      rangeaxislabel: json['rangeaxislabel'] as String?,
      rangeaxisdecimals: json['rangeaxisdecimals'] as int?,
      digitgroupseparator: json['digitgroupseparator'] as String?,
      targetlinevalue: (json['targetlinevalue'] as num?)?.toDouble(),
      attributevalues: json['attributevalues'],
      skiprounding: json['skiprounding'] as bool?,
      cumulative: json['cumulative'] as bool?,
      enddate: json['enddate'] == null
          ? null
          : DateTime.parse(json['enddate'] as String),
      legendshowkey: json['legendshowkey'] as bool?,
      colorset: json['colorset'] as String?,
      fontstyle: json['fontstyle'],
      percentstackedvalues: json['percentstackedvalues'] as bool?,
      userorganisationunit: json['userorganisationunit'] as bool?,
      lastupdatedby: json['lastupdatedby'] as int?,
      fixcolumnheaders: json['fixcolumnheaders'] as bool,
      showhierarchy: json['showhierarchy'] as bool?,
      sharing: json['sharing'],
      baselinelabel: json['baselinelabel'] as String?,
      showdata: json['showdata'] as bool?,
      paramreportingperiod: json['paramreportingperiod'] as bool?,
      uid: json['uid'] as String,
      fontsize: json['fontsize'] as String?,
      numbertype: json['numbertype'] as String?,
      visualizationid: json['visualizationid'] as int,
      rangeaxisminvalue: (json['rangeaxisminvalue'] as num?)?.toDouble(),
      coltotals: json['coltotals'] as bool?,
      type: json['type'] as String,
      paramparentorganisationunit: json['paramparentorganisationunit'] as bool?,
      targetlinelabel: json['targetlinelabel'] as String?,
      rangeaxissteps: json['rangeaxissteps'] as int?,
      outlieranalysis: json['outlieranalysis'],
      title: json['title'] as String?,
      rowsubtotals: json['rowsubtotals'] as bool?,
      rowtotals: json['rowtotals'] as bool?,
      created: json['created'] == null
          ? null
          : DateTime.parse(json['created'] as String),
      nospacebetweencolumns: json['nospacebetweencolumns'] as bool?,
      favorites: json['favorites'],
      relativeperiodsid: json['relativeperiodsid'] as int?,
      userorgunittype: json['userorgunittype'] as String?,
      externalaccess: json['externalaccess'] as bool?,
      colsubtotals: json['colsubtotals'] as bool?,
      sortorder: json['sortorder'] as int?,
      subscribers: json['subscribers'],
      regressiontype: json['regressiontype'] as String?,
      lastupdated: json['lastupdated'] == null
          ? null
          : DateTime.parse(json['lastupdated'] as String),
    );

Map<String, dynamic> _$$_VisualizationToJson(_$_Visualization instance) =>
    <String, dynamic>{
      'completedonly': instance.completedonly,
      'hideemptycolumns': instance.hideemptycolumns,
      'hidetitle': instance.hidetitle,
      'hideemptyrows': instance.hideemptyrows,
      'hideemptyrowitems': instance.hideemptyrowitems,
      'paramgrandparentorganisationunit':
          instance.paramgrandparentorganisationunit,
      'rangeaxismaxvalue': instance.rangeaxismaxvalue,
      'legenddisplaystyle': instance.legenddisplaystyle,
      'measurecriteria': instance.measurecriteria,
      'series': instance.series,
      'userorganisationunitchildren': instance.userorganisationunitchildren,
      'hidelegend': instance.hidelegend,
      'displaydensity': instance.displaydensity,
      'translations': instance.translations,
      'regression': instance.regression,
      'domainaxislabel': instance.domainaxislabel,
      'publicaccess': instance.publicaccess,
      'legenddisplaystrategy': instance.legenddisplaystrategy,
      'description': instance.description,
      'aggregationtype': instance.aggregationtype,
      'subtitle': instance.subtitle,
      'userorganisationunitgrandchildren':
          instance.userorganisationunitgrandchildren,
      'fixrowheaders': instance.fixrowheaders,
      'code': instance.code,
      'userid': instance.userid,
      'legendsetid': instance.legendsetid,
      'hidesubtitle': instance.hidesubtitle,
      'axes': instance.axes,
      'name': instance.name,
      'serieskey': instance.serieskey,
      'showdimensionlabels': instance.showdimensionlabels,
      'baselinevalue': instance.baselinevalue,
      'toplimit': instance.toplimit,
      'paramorganisationunit': instance.paramorganisationunit,
      'startdate': instance.startdate?.toIso8601String(),
      'rangeaxislabel': instance.rangeaxislabel,
      'rangeaxisdecimals': instance.rangeaxisdecimals,
      'digitgroupseparator': instance.digitgroupseparator,
      'targetlinevalue': instance.targetlinevalue,
      'attributevalues': instance.attributevalues,
      'skiprounding': instance.skiprounding,
      'cumulative': instance.cumulative,
      'enddate': instance.enddate?.toIso8601String(),
      'legendshowkey': instance.legendshowkey,
      'colorset': instance.colorset,
      'fontstyle': instance.fontstyle,
      'percentstackedvalues': instance.percentstackedvalues,
      'userorganisationunit': instance.userorganisationunit,
      'lastupdatedby': instance.lastupdatedby,
      'fixcolumnheaders': instance.fixcolumnheaders,
      'showhierarchy': instance.showhierarchy,
      'sharing': instance.sharing,
      'baselinelabel': instance.baselinelabel,
      'showdata': instance.showdata,
      'paramreportingperiod': instance.paramreportingperiod,
      'uid': instance.uid,
      'fontsize': instance.fontsize,
      'numbertype': instance.numbertype,
      'visualizationid': instance.visualizationid,
      'rangeaxisminvalue': instance.rangeaxisminvalue,
      'coltotals': instance.coltotals,
      'type': instance.type,
      'paramparentorganisationunit': instance.paramparentorganisationunit,
      'targetlinelabel': instance.targetlinelabel,
      'rangeaxissteps': instance.rangeaxissteps,
      'outlieranalysis': instance.outlieranalysis,
      'title': instance.title,
      'rowsubtotals': instance.rowsubtotals,
      'rowtotals': instance.rowtotals,
      'created': instance.created?.toIso8601String(),
      'nospacebetweencolumns': instance.nospacebetweencolumns,
      'favorites': instance.favorites,
      'relativeperiodsid': instance.relativeperiodsid,
      'userorgunittype': instance.userorgunittype,
      'externalaccess': instance.externalaccess,
      'colsubtotals': instance.colsubtotals,
      'sortorder': instance.sortorder,
      'subscribers': instance.subscribers,
      'regressiontype': instance.regressiontype,
      'lastupdated': instance.lastupdated?.toIso8601String(),
    };
